blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/ptnghia/internal-chat/wiki
    about: Check our comprehensive documentation and guides
  - name: 💬 Discussions
    url: https://github.com/ptnghia/internal-chat/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📋 Project Board
    url: https://github.com/ptnghia/internal-chat/projects
    about: View project progress and roadmap
  - name: 🚀 Getting Started
    url: https://github.com/ptnghia/internal-chat/blob/main/GETTING_STARTED.md
    about: Quick start guide for developers
